const express = require('express');
const app = express();
const server = require('http').Server(app);
const io = require('socket.io')(server);
const rooms = require('./state.js').rooms
const cwd = process.cwd()
app.use('/', express.static(cwd + '/dist'));

server.listen(process.env.PORT || 8081, function () {
  console.log('Listening on ' + server.address().port);
});

io.on('connection', async function (socket) {
  const userData = socket.handshake.auth
  const roomId = userData.roomId
  socket.join(roomId)
  const gameState = rooms.createRoom(roomId, io, userData.item_layer)
  rooms.connectToRoom(roomId, userData.userId)
  io.in(roomId).emit('broadcast', 'syncServerStateToClient', gameState)

  socket.on('READ_SERVER_GAME_STATE', () => {
    io.in(roomId).emit('broadcast', 'syncServerStateToClient', gameState)
  })

  socket.on('WRITE_PLAYER_STATE_TO_SERVER', (userId, playerState) => {
    const playerIndex = gameState.players.findIndex(player => player.id === userId)
    gameState.players
    if (playerIndex > -1) {
      gameState.players[playerIndex] = playerState
    } else {
      gameState.players.push(playerState)
    }
  })

  socket.on('serverGameStateUpdate', (action, data) => {
    switch (action) {
      case 'collectItem': {
        const itemIndex = gameState.items.findIndex(item => item.id === data.itemId)
        if (itemIndex < 0) {
          // already been collected by other player or the items may not be generated by server
        } else {
          // collect effect 
          gameState.items.splice(itemIndex, 1)
        }
      }
      default: {
        // unhandled action
      }
    }
  })

  socket.on('broadcast', (method, ...args) => {
    socket.to(roomId).emit('broadcast', method, ...args)
  })

  socket.on('disconnect', async function () {
    rooms.disconnectFromRoom(roomId, userData.userId)
    io.in(roomId).emit('broadcast', 'syncServerStateToClient', gameState)
  })
})
