// Tile map block's default category is one, so we don't need to set it mannually

export default {
  CATEGORY_MAP_BLOCK: 1,
  CATEGORY_TEAM_RED_PLAYER: 2,
  CATEGORY_TEAM_RED_BULLET: 4,
  CATEGORY_TEAM_BLUE_PLAYER: 8,
  CATEGORY_TEAM_BLUE_BULLET: 16,
  CATEGORY_MONSTER: 32,
  CATEGORY_MOSNTER_BULLET: 64,
  CATEGORY_TRANSPARENT: 128,
  CATEGORY_ITEM: 256,
}